language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lzaltzberg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lzaltzberg/react-test npm test
  -
after_success:
  - docker build -t lzaltzberg/multi-client ./client
  - docker build -t lzaltzberg/multi-nginx ./nginx
  - docker build -t lzaltzberg/multi-server ./server
  - docker build -t lzaltzberg/multi-worker ./worker
  #log in to the docker CLI
  - echo "$DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push lzaltzberg/multi-client
  - docker push lzaltzberg/multi-nginx
  - docker push lzaltzberg/multi-server
  - docker push lzaltzberg/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-453093575071"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY